# Dev
org.gradle.jvmargs=-Xmx5G
org.gradle.caching=true
org.gradle.configureondemand=true

# If your computer can handle it, turn this to true
org.gradle.parallel=false

net.minecraftforge.gradle.merge-source-sets=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

fabric.loom.multiProjectOptimisation=true
# Mod
mod.name=Habirance
mod.id=habirance
mod.group=endurteam
mod.version=0.2.0-SNAPSHOT
mod.author=Team Endur
mod.description=*
mod.license=LGPLv3 or later
mod.credits=*

# Stonecutter
stonecutter_enabled_platforms=fabricmc, neoforge, minecraftforge, quiltmc
stonecutter_enabled_common_versions=1.20.1, 1.21.1, 1.21.11
stonecutter_enabled_fabricmc_versions=1.20.1, 1.21.1, 1.21.11
stonecutter_enabled_minecraftforge_versions=1.21.1, 1.21.11
stonecutter_enabled_minecraftforge_renamer_versions=1.20.1
stonecutter_enabled_neoforge_versions=1.21.1, 1.21.11
# Fabric https://fabricmc.net/develop/
fabric_loader_version=0.18.4
fabric_mixin_version=0.17.0+mixin.0.8.7
mixinextras_version=0.5.3
# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
# NeoForge https://projects.neoforged.net/neoforged/neoforge/
java.version=21