plugins {
	`multiloader-loader`
	id("net.minecraftforge.gradle")
	id("net.minecraftforge.jarjar")
	id("net.minecraftforge.accesstransformers")
	id("net.minecraftforge.renamer")
}

println(
	"Java: ${providers.systemProperty("java.version").get()}, " +
		"JVM: ${providers.systemProperty("java.vm.version").get()} (${
			providers.systemProperty("java.vendor").get()
		}), " +
		"Arch: ${providers.systemProperty("os.arch").get()}"
)

// Creates a task named 'renameJar'
renamer.classes(tasks.named<Jar>("jar")) {
	// You need to point to the mappings you wish to apply, typically this is the Mapped names to SRG for older versions.
	// ForgeGradle/Mavenizer generate these files for the dependencies you declare. So you can use the helper.
	// Or you can specify the file or dependency if you host them yourself.
	map.from(minecraft.dependency.toSrgFile, renamer.mixin.generatedMappings)
	// This is publishable task so you can specify things such as the classifier
	archiveClassifier = "srg"
}

minecraft {
	mappings(
		if (commonMod.propOrNull("parchment_mappings") != null) "parchment" else "official",
		if (commonMod.propOrNull("parchment_mappings") != null)
			"${commonMod.minecraft_version}-${commonMod.prop("parchment_mappings")}" else commonMod.minecraft_version
	)

	setAccessTransformer(true)

	runs {
		configureEach {
			workingDir.convention(layout.projectDirectory.dir("run"))

			systemProperty ("forge.logging.markers", "REGISTRIES,CORE,CONFIG,SCAN,LOADING,NETWORK,DEBUG")

			systemProperty("forge.logging.console.level", "all")

			systemProperty("eventbus.api.strictRuntimeChecks", "true")

			systemProperty("mixin.env.disableRefMap", "true")

			//args ("-mixin.config=${commonMod.id}.mixins.json")

			//classpath(sourceSets.main.get())
		}

		register("client") {
			systemProperty("forge.enabledGameTestNamespaces", commonMod.id)
		}

		register("server") {
			systemProperty("forge.enabledGameTestNamespaces", commonMod.id)
			args("--nogui")
		}

		register("gameTestServer") {
			systemProperty("forge.enabledGameTestNamespaces", commonMod.id)
		}

		register("data") {
			workingDir = layout.projectDirectory.dir("run-data")

			args(
				"--mod",
				commonMod.id,
				"--all",
				"--output",
				layout.projectDirectory.dir("src/generated/resources"),
				"--existing",
				layout.projectDirectory.dir("src/main/resources")
			)
		}
	}
}

// Include resources generated by data generators.
sourceSets.named("main") {
	resources { srcDir(layout.projectDirectory.dir("src/generated/resources")) }
}

// This methods registers jarJar for the default jar task.
// The closure allows you to configure the task, instead of needing to do this:
jarJar.register() {
	archiveClassifier = null
}


minecraft.mavenizer(repositories)
repositories {
	maven(fg.forgeMaven)
	maven(fg.minecraftLibsMaven)
	exclusiveContent {
		forRepository {
			maven {
				name = "Sponge"
				url = uri("https://repo.spongepowered.org/repository/maven-public")
			}
		}
		filter {
			includeGroupAndSubgroups("org.spongepowered")
		}
	}
	mavenCentral()
	maven("https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/")
	maven("https://maven.terraformersmc.com/releases/")
	maven("https://maven.ryanliptak.com/")
	maven("https://maven.shedaniel.me/")
	maven("https://maven.minecraftforge.net/")
}

dependencies {
	// Specify the version of Minecraft to use.
	// Any artifact can be supplied so long as it has a "userdev" classifier artifact and is a compatible patcher artifact.
	// The "userdev" classifier will be requested and setup by ForgeGradle.
	// If the group id is "net.minecraft" and the artifact id is one of ["client", "server", "joined"],
	// then special handling is done to allow a setup of a vanilla dependency without the use of an external repository.
	implementation(minecraft.dependency("net.minecraftforge:forge:${commonMod.minecraft_version}-${commonMod.prop("minecraftforge_version")}"))

	// Example mod dependency with JEI
	// The JEI API is declared for compile time use, while the full JEI artifact is used at runtime
	//compileOnly "mezz.jei:jei-${mc_version}-common-api:${jei_version}"
	//compileOnly "mezz.jei:jei-${mc_version}-forge-api:${jei_version}"
	//runtimeOnly "mezz.jei:jei-${mc_version}-forge:${jei_version}"

	implementation(renamer.dependency("com.github.glitchfiend:TerraBlender-forge:${commonMod.minecraft_version}-${commonMod.prop("terrablender_version")}") {
		map.from(minecraft.dependency.toSrgFile)
	})

	implementation(renamer.dependency("software.bernie.geckolib:geckolib-forge-${commonMod.minecraft_version}:${commonMod.prop("geckolib_version")}") {
		map.from(minecraft.dependency.toSrgFile)
	})
	implementation("com.eliotlash.mclib:mclib:20")

	if (stonecutter.eval(stonecutter.current.version, "<=1.20.1")) {
		runtimeOnly(renamer.dependency("squeek.appleskin:appleskin-forge:${commonMod.prop("appleskin_version_forge")}") {
			map.from(minecraft.dependency.toSrgFile)
		})
	}

	"jarJar"("net.fabricmc:sponge-mixin:${commonMod.prop("fabric_mixin_version")}") {
		jarJar.configure(this)
		{
			setRange("[${commonMod.prop("fabric_mixin_version")},)")
		}
	}
	annotationProcessor("io.github.llamalad7:mixinextras-common:${commonMod.prop("mixinextras_version")}")
	"jarJar"("io.github.llamalad7:mixinextras-forge:${commonMod.prop("mixinextras_version")}") {
		jarJar.configure(this)
		{
			setRange("[${commonMod.prop("mixinextras_version")},)")
		}
	}

	// Example mod dependency using a mod jar from ./libs with a flat dir repository
	// This maps to ./libs/coolmod-${mc_version}-${coolmod_version}.jar
	// The group id is ignored when searching -- in this case, it is "blank"
	// NOTE: Support for deobfuscated dependencies has not yet been added in ForgeGradle 7.
	//implementation "blank:coolmod-${mc_version}:${coolmod_version}"

	// For more info:
	// http://www.gradle.org/docs/current/userguide/artifact_dependencies_tutorial.html
	// http://www.gradle.org/docs/current/userguide/dependency_management.html
}
renamer.mappings.from(minecraft.dependency.toSrgFile)

tasks.withType<JavaCompile>().configureEach {
	options.encoding = "UTF-8" // Use the UTF-8 charset for Java compilation
}

tasks {
	processResources {
		exclude("${mod.id}.accesswidener")
	}

	register<Copy>("copyAT") {
		val atFile =
			project(":common").file("src/main/resources/accesstransformers/accesstransformer-${commonMod.minecraft_version}.cfg")
		from(atFile) {
			rename("accesstransformer-${commonMod.minecraft_version}.cfg", "accesstransformer.cfg")
		}
		setDuplicatesStrategy(DuplicatesStrategy.INHERIT)
		into("src/main/resources/META-INF")
		mustRunAfter(common.project.tasks.getByName("stonecutterMerge"))
	}
}

tasks.named("stonecutterPrepare") {
	finalizedBy(tasks.named("copyAT"))
}

sourceSets.forEach {
	val dir = layout.buildDirectory.dir("sourcesSets/$it.name")
	it.output.setResourcesDir(dir)
	it.java.destinationDirectory = dir
}